# Generated by Django 4.1.7 on 2023-07-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('des', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='IMAGE')),
            ],
        ),
    ]
